<?php
/**
 * Implementation of hook_init().
 */
function eureka_ajax_init() {
    // Include the js file
    drupal_add_js(drupal_get_path('module', 'eureka_ajax') . '/eureka_ajax.js');
}

/**
 * Implementation of hook_menu().
 */
function eureka_ajax_menu() {
//    $items = array();
//
//    // Create a Drupal page to display our AJAX link.
//    $items['eureka/page'] = array(
//        'title' => 'Test Page',
//        'page callback' => 'test_page_callback',
//        'access arguments' => array('access content'),
//        'type' => MENU_NORMAL_ITEM,
//    );
//
//    // Create a path to send our AJAX request to.
//    $items['eureka/ajax'] = array(
//        'title' => 'Ajax Request',
//        'page callback' => 'ajax_request_callback',
//        'access callback' => TRUE,
//        'type' => MENU_CALLBACK,
//    );
//
//    return $items;
}

/**
 * Callback function for /eureka/page.
 */
function test_page_callback() {
    return theme('ajax_link');
}

/**
 * Implementation of hook_theme().
 */
function eureka_ajax_theme() {
    return array(
        'ajax_link' => array(),
    );
}

/**
 * Implementation of theme_ajax_link().
 */
function theme_ajax_link() {
    return l(t('What is the date and time?'), 'eureka/ajax', array(
            'attributes' => array(
                'id' => 'eureka-ajax')
        )
    );
}

/**
 * Callback function for /eureka/ajax.
 */
function ajax_request_callback() {
    if ($_POST['from_js']) {
        // Return the time if the from_js request para is set to true
        $response = array(
            'message' => t('It is approximately !date', array('!date' => date('M j Y h:i:s'))),
        );
        drupal_json_output($response);
        exit;
    } else {
        // Return an empty json array for incorrect request
        drupal_json_output(array());
        exit;
    }
}
