
<?php

function login_js_menu(){
    $items = array();
//	http://localhost/drupal-7.52/?q=login_page
    $items['login_page'] = array(
        'title' => 'Login Page by JavaScript',
        'description' => 'Description of Login Page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('login_js_page'),
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['api/login_page'] =  array(
        'title' => 'op',
        'page callback' => 'login_js_ajax',
        'access arguments' => array('access content'),
        'access callback' => true,
        'type' => MENU_CALLBACK,
        'delivery callback' => 'drupal_json_output',
    );

    return $items;
}

function login_js_page($form, &$form_state){

    drupal_add_js(drupal_get_path('module','login_js') . '/login_js.js', 'file');

     array();
//    echo 'd';

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'user name',
        '#required' => TRUE,
    );
    $form['password'] = array(
        '#type' => 'password',
        '#title' => 'Password',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Login',
    );

    $form['#suffix'] = "<div id='errors'></div>";

    return $form;

}

/*function redirect ajax submit*/
function login_js_ajax() {
//    $callback = check_plain($_REQUEST['callback']);
//    drupal_add_http_header('Content-Type', 'application/json');
    if(isset($_POST)){
//        print_r($_POST);

        return json_encode(['name'=>$_POST['name'],'password'=>'352']);
    }
    return json_encode(['name'=>"",'password'=>'123']);

}
