<?php
/**
 * Created by PhpStorm.
 * User: osamamohsen
 * Date: 18/12/16
 * Time: 04:54 ص
 */

function test_menu(){
    $items = array();
//	http://localhost/drupal-7.52/?q=testpage
//    $items['testpage'] = array(
//        'title' => 'Test Page',
//        'description' => 'Description of Test Page',
//        'page callback' => 'drupal_get_form',
//        'page arguments' => array('test_page'),
//        'access callback' => 'user_access',
//        'access arguments' => array('access content'),
//        'type' => MENU_NORMAL_ITEM
//    );
    return $items;
}
//

function _form_test_add(){
    $form = array();

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Name Of Test',
        '#required' => TRUE,
    );

    $form['title'] = array(
        '#type' => 'textfield',
        '#title' => 'Title Of Test',
        '#required' => TRUE,
    );

    $form['body'] = array(
        '#type' => 'textarea',
        '#title' => 'Body Of Test',
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit a Test Page',
        '#ajax' => array(
            'callback' => '_form_test_add_callback',
            'progess' => array('type' => 'throbber'),
            'wrapper' => 'formwrapper',
            'method' => 'replace',
            'effect' => 'fade',
        ),
    );

    $form['#prefix'] = '<div id="formwrapper">';
    $form['#suffix'] = '</div>';

//    $form['#submit'][] = '_form_test_add_callback';
    return $form;
}

function _form_test_add_callback($form,$form_state){
////echo "<pre>";
////print_r($form);
////exit;
//
    $ress = drupal_validate_form('_form_test_add', $form, $form_state);
    $errors = form_get_errors();

    if (form_get_errors()) {
        $form_state['rebuild'] = TRUE;
        return $form;
    }
    if(!form_get_errors()){

        global $user;

        $node = new stdClass();
        $node->type = 'Test';
//        $newnode->name = $form_state['input']['name'];
//        $newnode->title['und'][0]['value'] = $form_state['input']['title'];
//        $newnode->body['und'][0]['value'] = $form_state['input']['body'];

        node_object_prepare($node);
        $node->language = LANGUAGE_NONE;
        $node->uid = $user->uid;
        $node->status = 1; //(1 or 0): published or not
        $node->promote = 0; //(1 or 0): promoted to front page
        $node->comment = 1; // 0 = comments disabled, 1 = read only, 2 = read/write

        // Term reference (taxonomy) field
        $node->name[$node->language][]['tid'] = $form_state['values']['name'];
        $node->title[$node->language][]['tid'] = $form_state['values']['title'];
        $node->body[$node->language][]['tid'] = $form_state['values']['body'];



//        $node = node_submit($node);
        node_save($node);
    }else{
        echo "errr";
    }
    return $form;


}
//echo "<pre>";
//print_r($variables);
//exit;


function test_preprocess_page(&$variables){
    $arg = arg();
    if($arg[0] == 'testpage'){
        $form = drupal_get_form('_form_test_add');
        array_unshift($variables['page']['content']['system_main'],$form);
    }
}